#!/bin/bash
#
# Copyright 2022-present Wistron. All Rights Reserved.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

#shellcheck disable=SC1091
. /usr/local/bin/openbmc-utils.sh

PID_FILE=/var/run/mux-util.pid

trap pid_file_remove INT TERM QUIT EXIT

usage() {
    prog=$(basename "$0")
    printf "Usage: %s --get <i2c / uart>\n" "$prog"
    printf "Usage: %s --set <i2c / uart> <bmc / cpu>\n" "$prog"
}

duplicate_process_check() {
    if [ -f $PID_FILE ]; then
        printf "Another process is running...\n"
        exit 255
    fi

    touch $PID_FILE
    # Check the PID file
    if [ ! -f $PID_FILE ]; then
        printf "Cannot create PID file !\n"
        exit 255
    fi
    echo $$ > $PID_FILE
}

pid_file_remove() {
    local pid_num

    if [ -f $PID_FILE ]; then
        pid_num=$(cat $PID_FILE)
        if [ "$pid_num" = "$$" ]; then
            rm $PID_FILE
        fi
    fi
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

duplicate_process_check

OPERATION="$1"
shift

if [ "$OPERATION" = "--get" ]; then
    if declare -F platform_get_mux_master &> /dev/null; then
        platform_get_mux_master "$@"
    else
        get_mux_master "$@"
    fi
    ret=$?

    if [ $ret -eq 1 ]; then
        usage
    fi
elif [ "$OPERATION" = "--set" ]; then
    if declare -F platform_set_mux_master &> /dev/null; then
        platform_set_mux_master "$@"
    else
        set_mux_master "$@"
    fi
    ret=$?

    if [ $ret -eq 1 ]; then
        usage
    fi
else
    usage
    exit 1
fi

exit $ret
