#!/bin/bash
#
# Copyright 2022-present Wistron. All Rights Reserved.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

#shellcheck disable=SC1091
. /usr/local/bin/openbmc-utils.sh

PID_FILE=/var/run/power-util.pid

trap pid_file_remove INT TERM QUIT EXIT

usage() {
    prog=$(basename "$0")
    printf "Usage: %s FRU [on|off|cycle|reset] [all|COMPONENT]\n" "$prog"
    printf "\n"
    printf "FRU        : COMPONENT"
    printf "\n---------- : ----------\n"
    print_power_fru_comp
}

duplicate_process_check() {
    if [ -f $PID_FILE ]; then
        printf "Another process is running...\n"
        exit 255
    fi

    touch $PID_FILE
    # Check the PID file
    if [ ! -f $PID_FILE ]; then
        printf "Cannot create PID file !\n"
        exit 255
    fi
    echo $$ > $PID_FILE
}

pid_file_remove() {
    local pid_num

    if [ -f $PID_FILE ]; then
        pid_num=$(cat $PID_FILE)
        if [ "$pid_num" = "$$" ]; then
            rm $PID_FILE
        fi
    fi
}

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

duplicate_process_check

FRU="$1"
shift
OPERATION="$1"
shift
COMPONENT="$1"
shift

if [ "$(is_valid_power_fru "$FRU")" = "false" ]; then
    usage
    exit 1
fi

if [ "$#" -eq 0 ]; then
    if [ "$COMPONENT" = "" ]; then
        COMPONENT="all"
    fi

    do_power_operation "$FRU" "$OPERATION" "$COMPONENT"
    ret=$?
else
    ret=1
fi

if [ "$ret" -eq 1 ]; then
    usage
fi

exit $ret
